const doctorView = document.querySelector('#doctorView'), screenView = document.querySelector('#screenView'), form = document.querySelector('#callForm'), nameInput = document.querySelector('#patientName'), roomInput = document.querySelector('#roomNumber'), specialtyInput = document.querySelector('#specialty'), voiceInput = document.querySelector('#repeatVoice'), channel = 'BroadcastChannel' in window ? new BroadcastChannel('salud-en-turno') : null; let tvWindow = null, toastTimer;
const time = () => new Intl.DateTimeFormat('es-CO', { hour: '2-digit', minute: '2-digit', hour12: true }).format(new Date());
const calls = () => { try { return JSON.parse(localStorage.getItem('saludEnTurnoCalls')) || [] } catch { return [] } };
const current = () => { try { return JSON.parse(localStorage.getItem('saludEnTurnoCurrent')) } catch { return null } };
const saveCalls = x => localStorage.setItem('saludEnTurnoCalls', JSON.stringify(x)); const saveCurrent = x => localStorage.setItem('saludEnTurnoCurrent', JSON.stringify(x));
function toast(message) { const x = document.querySelector('#toast'); x.textContent = message; x.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => x.classList.remove('show'), 3500) }
function speak(call) { if (!('speechSynthesis' in window) || !call.voice) return; speechSynthesis.cancel(); const x = new SpeechSynthesisUtterance(`Atención, ${call.name}. Por favor dirigirse al consultorio número ${call.room}.`); x.lang = 'es-CO'; x.rate = .85; speechSynthesis.speak(x) }
function history() { const box = document.querySelector('#historyList'); if (!box) return; const data = calls(); if (!data.length) { box.innerHTML = '<p class="empty-state">Aún no hay pacientes llamados hoy.</p>'; return } box.innerHTML = data.slice(0, 8).map((x, i) => `<article class="history-row"><span class="history-number">${String(data.length - i).padStart(2, '0')}</span><div><div class="history-name">${x.name}</div><div class="history-meta">${x.specialty} · Consultorio ${x.room}</div></div><time class="history-time">${x.time}</time></article>`).join('') }
function flash() { const x = document.querySelector('#screenView'); if (!x) return; x.classList.remove('call-flash'); void x.offsetWidth; x.classList.add('call-flash') }
function screen(call, animate = false) { const name = document.querySelector('#tvName'); if (!name) return; const status = document.querySelector('#tvStatus'), instruction = document.querySelector('#tvInstruction'), room = document.querySelector('#tvRoomBox'); if (!call) { status.textContent = 'BIENVENIDOS'; name.textContent = 'Espere su llamado'; instruction.textContent = 'Nuestro equipo le avisará cuando sea su turno.'; room.innerHTML = '<span>CONSULTORIO</span><strong>—</strong>'; room.classList.add('is-empty'); return } status.textContent = 'ES TU TURNO'; name.textContent = call.name; instruction.textContent = `Por favor, dirígete a ${call.specialty}.`; room.innerHTML = `<span>CONSULTORIO</span><strong>${call.room}</strong>`; room.classList.remove('is-empty'); if (animate) flash() }
function preview() { document.querySelector('#previewName').textContent = nameInput.value.trim() || 'Tu nombre aparecerá aquí'; document.querySelector('#previewRoom').textContent = `CONSULTORIO ${roomInput.value}`; document.querySelector('#doctorRoomLabel').textContent = roomInput.value }
function setTheme(value) { document.body.classList.toggle('light', value === 'light'); localStorage.setItem('saludEnTurnoTheme', value); const label = document.querySelector('#themeButton span'); if (label) label.textContent = value === 'light' ? 'Modo oscuro' : 'Modo claro' }
form?.addEventListener('submit', e => { e.preventDefault(); const name = nameInput.value.trim().replace(/\s+/g, ' '); if (name.length < 3) { toast('Escribe el nombre completo del paciente.'); return } const call = { name, room: roomInput.value, specialty: specialtyInput.value, voice: voiceInput.checked, time: time(), timestamp: Date.now() }; const data = calls(); data.unshift(call); saveCalls(data); saveCurrent(call); history(); channel?.postMessage({ type: 'call', call }); if (tvWindow && !tvWindow.closed) tvWindow.postMessage({ type: 'call', call }, '*'); speak(call); toast(`${name} fue llamado al consultorio ${call.room}.`); nameInput.value = ''; preview() });
nameInput?.addEventListener('input', preview); roomInput?.addEventListener('change', preview); document.querySelector('#themeButton')?.addEventListener('click', () => setTheme(document.body.classList.contains('light') ? 'dark' : 'light')); document.querySelector('#testSound')?.addEventListener('click', () => speak({ name: 'Paciente de prueba', room: roomInput.value, voice: true })); document.querySelector('#openScreen')?.addEventListener('click', () => { tvWindow = window.open(`${location.pathname}?pantalla=tv`, 'pantallaSala'); if (!tvWindow) toast('Permite las ventanas emergentes para abrir la pantalla.') }); document.querySelector('#clearHistory')?.addEventListener('click', () => { saveCalls([]); history() }); document.querySelector('#historyButton')?.addEventListener('click', () => document.querySelector('.recent-section').scrollIntoView({ behavior: 'smooth' }));
channel && (channel.onmessage = e => { if (e.data?.type === 'call') { screen(e.data.call, true); speak(e.data.call) } }); window.addEventListener('message', e => { if (e.data?.type === 'call') { screen(e.data.call, true); speak(e.data.call) } }); window.addEventListener('storage', e => { if (e.key === 'saludEnTurnoCurrent') screen(current(), true) });
if (new URLSearchParams(location.search).get('pantalla') === 'tv') { doctorView.hidden = true; screenView.hidden = false; screen(current()); document.querySelector('#screenConnection')?.classList.add('connected') } else { setTheme(localStorage.getItem('saludEnTurnoTheme') || 'dark'); history(); preview() } setInterval(() => { const x = document.querySelector('#tvClock'), y = document.querySelector('#previewTime'); if (x) x.textContent = time(); if (y) y.textContent = time() }, 1000);
